name = "LadderOperators"
uuid = "d27c24bd-84bf-4c52-914b-d12f8784db43"
authors = ["Lukas Grunwald <lukas.grunwald@rwth-aachen.de>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[targets]
test = ["Test", "Combinatorics"]